2024-09-29 13:34:34,820 - INFO - Démarrage de l'exécution
2024-09-29 13:34:34,820 - INFO - Chargement du modèle depuis ../src/stylegan3-t-ffhq-1024x1024.pkl...
2024-09-29 13:34:42,749 - INFO - Modèle chargé avec succès.
2024-09-29 13:34:42,750 - INFO - ImageGenerator initialisé avec succès.
2024-09-29 13:34:42,751 - INFO - Début de la projection avec 15000 étapes.
2024-09-29 13:34:42,751 - ERROR - Une erreur est survenue
2024-09-29 13:34:42,751 - ERROR - Détails de l'exception : 
Traceback (most recent call last):
  File "/notebooks/scripts/main.py", line 70, in main
    generator.project(nb_steps=PROJ_NB_STEPS)
  File "/notebooks/scripts/ImageGenerator.py", line 123, in project
    image = self.load_image()
            ^^^^^^^^^^^^^^^^^
TypeError: ImageGenerator.load_image() missing 1 required positional argument: 'image_to_load'
